id: P93198143
initial_creation_type: ocr
source_metadata:
  volumes:
    e4465cd7b46b4459a27337fa3ddc50c9:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
