id: D4664B44A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-08T09:37:21+00:00'
last_modified: '2022-05-30T06:45:33.985994+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    8ba5:
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      order: 26
      base_file: 8ba5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
